# (C) Crown Copyright, Met Office. All rights reserved.
#
# This file is part of cube_helper and is released under the
# BSD 3-Clause license.
# See LICENSE in the root of the repository for full licensing details.

# Generated by Django 3.2 on 2022-07-19 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "version",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Version"
                    ),
                ),
                ("url", models.URLField(blank=True, null=True, verbose_name="URL")),
                (
                    "summary",
                    models.CharField(
                        blank=True, max_length=4000, null=True, verbose_name="Summary"
                    ),
                ),
                (
                    "doi",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="DOI"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=4000, null=True, verbose_name="Reference"
                    ),
                ),
                (
                    "license",
                    models.URLField(blank=True, null=True, verbose_name="License"),
                ),
                (
                    "date_downloaded",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date downloaded"
                    ),
                ),
                (
                    "creator",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Creator"
                    ),
                ),
                (
                    "project",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Project"
                    ),
                ),
            ],
            options={
                "verbose_name": "Dataset",
                "unique_together": {("name", "version")},
            },
        ),
        migrations.CreateModel(
            name="DataFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="File name")),
                (
                    "incoming_directory",
                    models.CharField(
                        max_length=4096, verbose_name="Incoming directory"
                    ),
                ),
                (
                    "directory",
                    models.CharField(
                        blank=True, max_length=4096, null=True, verbose_name="Directory"
                    ),
                ),
                ("size", models.BigIntegerField(verbose_name="File size")),
                ("checksum_value", models.CharField(max_length=200)),
                (
                    "checksum_type",
                    models.CharField(
                        choices=[
                            ("SHA256", "SHA256"),
                            ("MD5", "MD5"),
                            ("ADLER32", "ADLER32"),
                        ],
                        max_length=20,
                    ),
                ),
                ("online", models.BooleanField(default=True, verbose_name="Online?")),
                (
                    "start_time",
                    models.FloatField(blank=True, null=True, verbose_name="Start time"),
                ),
                (
                    "end_time",
                    models.FloatField(blank=True, null=True, verbose_name="End time"),
                ),
                (
                    "time_units",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Time units"
                    ),
                ),
                (
                    "calendar",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("standard", "standard"),
                            ("gregorian", "gregorian"),
                            ("proleptic_gregorian", "proleptic_gregorian"),
                            ("noleap", "noleap"),
                            ("365_day", "365_day"),
                            ("360_day", "360_day"),
                            ("julian", "julian"),
                            ("all_leap", "all_leap"),
                            ("366_day", "366_day"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Calendar",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Frequency"
                    ),
                ),
                (
                    "standard_name",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Standard name",
                    ),
                ),
                (
                    "long_name",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="Long name"
                    ),
                ),
                (
                    "var_name",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Var name"
                    ),
                ),
                (
                    "units",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Units"
                    ),
                ),
                (
                    "dimensions",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Dimensions"
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dmt_app.dataset",
                        verbose_name="Dataset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Data File",
                "unique_together": {("name", "incoming_directory")},
            },
        ),
    ]
