name: docs_build_test

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', ]
        django-version: ['3.2', ]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sed -i s/^Django$/Django\=\=${{ matrix.django-version }}/g requirements.txt
        sed -i 's/^# sphinx/sphinx/g' requirements.txt
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test that the documentation builds successfully
      run: |
        export PYTHONPATH=$GITHUB_WORKSPACE
        cd $PYTHONPATH/docs
        make html
