name: Check style with flake8

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install flake8
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Check style with flake8
      run: |
        flake8 .