name: Check style with pycodestyle

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pycodestyle
      run: |
        python -m pip install --upgrade pip
        pip install pycodestyle
    - name: Check style with pycodestyle
      run: |
        pycodestyle --max-line-length=88 .