name: Check code with pylint

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", ]
        django-version: ['3.2', ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sed -i s/^Django$/Django\=\=${{ matrix.django-version }}/g requirements.txt
        sed -i 's/^# pylint/pylint/g' requirements.txt
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Report pylint version
      run: |
        pylint --version
    - name: Check dmt_app code with pylint (IGNORE TODOs)
      run: |
        pylint -d fixme dmt_app
    - name: Check dmt_site code with pylint
      run: |
        pylint dmt_site
    - name: Check bin directory with pylint
      run: |
        pylint bin
    - name: Check docs/source/conf.py code with pylint
      run: |
        pylint docs/source/conf.py
